### ISSUE TITLE
"must specify a full WebSocket URL" error when running votebot container

### ISSUE THREAD

**Issue by yayoi-k** [midl-dev/polkadot-k8s#33]
Full error message which repeats:
2023-04-02 05:44:29          API-WS: Error: You must specify a full WebSocket URL, including hostname. Relative URLs are not supported.
    at WebSocketClient.connect (/app/node_modules/websocket/lib/WebSocketClient.js:145:15)
    at new W3CWebSocket (/app/node_modules/websocket/lib/W3CWebSocket.js:62:18)
    at WsProvider.connect (/app/node_modules/@polkadot/rpc-provider/cjs/ws/index.js:448:9)
    at WsProvider.connectWithRetry (/app/node_modules/@polkadot/rpc-provider/cjs/ws/index.js:480:20)
    at Timeout._onTimeout (/app/node_modules/@polkadot/rpc-provider/cjs/ws/index.js:483:16)

index.ts contains the following line which uses NODE_ENDPOINT environment variable and creates a complete URL:
```
const provider = new WsProvider(`ws://${process.env.NODE_ENDPOINT}:9944`);
```
I believe this line is the issue.  I've tried using both hostnames and IP addresses in the NODE_ENDPOINT environment variable and continue to receive this error.  There seems to be an issue with how this line composes the URL.

**Comment by nicolasochem** [comment]
It works for me, my endpoint is simply `private-node`. Are you using the container within the helm chart or in isolation? Can you try adding debug statements to make sure your env var is passed correctly to the script?

**Comment by yayoi-k** [comment]
Thanks for your help.  Yes, I'm running the container in isolation.  I did create a section up early in the script execution which outputs all the environment variables.
console.log("Environment Variables Output Check:");
  console.log("***");
  console.log(`Chain:                         ${process.env.CHAIN}`);
  console.log(`Stash account address:         ${process.env.STASH_ACCOUNT_ADDRESS!}`);
  console.log(`Stash account alias:           ${process.env.STASH_ACCOUNT_ALIAS}`);
  console.log(`proxy account mnemonic:        ${process.env.PROXY_ACCOUNT_MNEMONIC!}`);
  console.log(`proxy acct mnemonic mispelled: ${process.env.PROXY_ACOUNT_MNEMONIC}`);
  console.log(`Voting proxy account alias:    ${process.env.PROXY_ACCOUNT_ALIAS}`);
  console.log(`Node RPC endpoint in use:      ${process.env.NODE_ENDPOINT}`);
  console.log(`Vote repo in use:              ${process.env.VOTE_REPO}`);
console.log("***");

There are some typo's and inconsistencies in the script so I started to wonder if others are using this as it's written here.  Examples:
- Line 7: PROXY_ACOUNT_MNEMONIC misspelled and doesn't match any variables in the code.  
- Some of the variables in the code have an exclamation points at the end of them, which makes them even further from matching up with the environment variable examples at the top.  For example "PROXY_ACCOUNT_MNEMONIC!" on line 48.  and "STASH_ACCOUNT_ADDRESS!" on line 50.  “!” is ignored when declaring environment variables, so the script appends a “!” To the end of the data in the environment variable.

It could make sense to move the 'console log' section that starts at 65 up as high as possible in the code, as this section seems to serve as a sanity check on the variables that are stored.  Right now if there are issues the script typically fails out before the 'console log' on 65 is ever output.

As a sanity check I tried forking the project, replacing the process.env entries with the values themselves and building the container and that seems to allow the script to work successfully completely.

My current issue is line 60:
const voteBotKey = keyring.addFromUri(process.env.PROXY_ACCOUNT_MNEMONIC!);
If I remove the “!” from the script then the container won’t build.  If I leave the exclamation point in, then it seems like a “!” is appended to the end of the mnemonic (I think) and then the container won’t run and gets the following error:

Error: Unable to match provided value to a secret URI
    at keyExtractSuri (/app/node_modules/@polkadot/util-crypto/cjs/key/extractSuri.js:20:11)
    at Keyring.createFromUri (/app/node_modules/@polkadot/keyring/cjs/keyring.js:239:40)
    at Keyring.addFromUri (/app/node_modules/@polkadot/keyring/cjs/keyring.js:172:30)
    at /app/index.js:110:42
    at step (/app/index.js:51:23)
    at Object.next (/app/index.js:32:53)
    at fulfilled (/app/index.js:23:58)

**Comment by yayoi-k** [comment]
With further testing I removed all quotes from the environment variables file and I got the script to run successfully, that appeared to be the issue for me all along.  Its standard to include quotes in environment variables when there are spaces in the contents, but it appears in this case there needs to be no quotes.
